-- Create the blogs table
create table blogs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  language text not null,
  translations jsonb default '{}'::jsonb
);

-- Set up Row Level Security (RLS)
alter table blogs enable row level security;

-- Policy to allow read access for everyone
create policy "Enable read access for all users"
on blogs for select
using (true);

-- Policy to allow insert access for everyone (for hackathon transparency/ease)
-- In production, you'd want authenticated users only
create policy "Enable insert for all users"
on blogs for insert
with check (true);

-- Policy to allow update for all users (for translations)
create policy "Enable update for all users"
on blogs for update
using (true);
